services:
    postgres:
        image: postgres:15-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: your_database_name
            POSTGRES_HOST_AUTH_METHOD: trust
