services:
    postgres:
        image: postgres:15-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: $DATABASE_DB
            POSTGRES_USER: $DATABASE_USER
            POSTGRES_PASSWORD: $DATABASE_PASSWORD
